### ISSUE TITLE
crash (maybe just with fish)

### ISSUE THREAD

**Issue by ec1oud** [rburchell/literm_old#25]
```Thread 1 "yat" received signal SIGSEGV, Segmentation fault.
0x00007fffec171fc5 in QString::isNull (this=0x8)
    at /home/rutledge/dev/qt59-dbg/qtbase/include/QtCore/../../../../qt59/qtbase/src/corelib/tools/qstring.h:780
780         inline bool isNull() const { return d == Data::sharedNull(); }
(gdb) bt
#0  0x00007fffec171fc5 in QString::isNull (this=0x8)
    at /home/rutledge/dev/qt59-dbg/qtbase/include/QtCore/../../../../qt59/qtbase/src/corelib/tools/qstring.h:780
#1  0x00007fffec184144 in QString::clear (this=0x8)
    at /home/rutledge/dev/qt59-dbg/qtbase/include/QtCore/../../../../qt59/qtbase/src/corelib/tools/qstring.h:905
#2  0x00007fffec181a8d in Block::clear (this=0x0) at ../../backend/block.cpp:63
#3  0x00007fffec18c87f in ScreenData::clearLine (this=0x6fb6d0, point=...) at ../../backend/screen_data.cpp:175
#4  0x00007fffec191b42 in Cursor::clearLine (this=0x6fc6c0) at ../../backend/cursor.cpp:446
#5  0x00007fffec17525f in Parser::decodeCSI (this=0x6fa1d0, character=75 'K') at ../../backend/parser.cpp:630
#6  0x00007fffec1729a5 in Parser::addData (this=0x6fa1d0, data=...) at ../../backend/parser.cpp:189
#7  0x00007fffec17cc8a in Screen::readData (this=0x6f8d90, data=...) at ../../backend/screen.cpp:420
#8  0x00007fffec17fb45 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<QByteArray const&>, void, void (Screen::*)(QByteArray const&)>::call (f=(void (Screen::*)(Screen * const, const QByteArray &)) 0x7fffec17cc60 <Screen::readData(QByteArray const&)>, 
    o=0x6f8d90, arg=0x7fffffffd8a0)
    at /home/rutledge/dev/qt59-dbg/qtbase/include/QtCore/../../../../qt59/qtbase/src/corelib/kernel/qobjectdefs_impl.h:136
#9  0x00007fffec17f87d in QtPrivate::FunctionPointer<void (Screen::*)(QByteArray const&)>::call<QtPrivate::List<QByteArray const&>, void>
    (f=(void (Screen::*)(Screen * const, const QByteArray &)) 0x7fffec17cc60 <Screen::readData(QByteArray const&)>, o=0x6f8d90, 
    arg=0x7fffffffd8a0)
    at /home/rutledge/dev/qt59-dbg/qtbase/include/QtCore/../../../../qt59/qtbase/src/corelib/kernel/qobjectdefs_impl.h:169
#10 0x00007fffec17f34d in QtPrivate::QSlotObject<void (Screen::*)(QByteArray const&), QtPrivate::List<QByteArray const&>, void>::impl (
    which=1, this_=0x6fcb70, r=0x6f8d90, a=0x7fffffffd8a0, ret=0x0)
    at /home/rutledge/dev/qt59-dbg/qtbase/include/QtCore/../../../../qt59/qtbase/src/corelib/kernel/qobject_impl.h:120
#11 0x00007ffff6c70e8d in QtPrivate::QSlotObjectBase::call (a=<optimized out>, r=0x6f8d90, this=<optimized out>)
    at ../../include/QtCore/../../../../qt59/qtbase/src/corelib/kernel/qobject_impl.h:101
#12 QMetaObject::activate (sender=sender@entry=0x6f8da8, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=1, 
    argv=argv@entry=0x7fffffffd8a0) at /home/rutledge/dev/qt59/qtbase/src/corelib/kernel/qobject.cpp:3749
#13 0x00007ffff6c713ef in QMetaObject::activate (sender=0x6f8da8, m=<optimized out>, local_signal_index=1, argv=0x7fffffffd8a0)
    at /home/rutledge/dev/qt59/qtbase/src/corelib/kernel/qobject.cpp:3628
#14 0x00007fffec19b3fb in YatPty::readyRead (this=0x6f8da8, _t1=...) at .moc/moc_yat_pty.cpp:145
#15 0x00007fffec16eb32 in YatPty::readData (this=0x6f8da8) at ../../backend/yat_pty.cpp:154
#16 0x00007fffec16f327 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (YatPty::*)()>::call(void (YatPty::*)(), YatPty*, void**) (f=(void (YatPty::*)(YatPty * const)) 0x7fffec16eabe <YatPty::readData()>, o=0x6f8da8, arg=0x7fffffffdae0)
    at /home/rutledge/dev/qt59-dbg/qtbase/include/QtCore/../../../../qt59/qtbase/src/corelib/kernel/qobjectdefs_impl.h:136
#17 0x00007fffec16f2b9 in QtPrivate::FunctionPointer<void (YatPty::*)()>::call<QtPrivate::List<>, void>(void (YatPty::*)(), YatPty*, void**) (f=(void (YatPty::*)(YatPty * const)) 0x7fffec16eabe <YatPty::readData()>, o=0x6f8da8, arg=0x7fffffffdae0)
    at /home/rutledge/dev/qt59-dbg/qtbase/include/QtCore/../../../../qt59/qtbase/src/corelib/kernel/qobjectdefs_impl.h:169
#18 0x00007fffec16f223 in QtPrivate::QSlotObject<void (YatPty::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x6fa880, r=0x6f8da8, a=0x7fffffffdae0, ret=0x0)
    at /home/rutledge/dev/qt59-dbg/qtbase/include/QtCore/../../../../qt59/qtbase/src/corelib/kernel/qobject_impl.h:120
#19 0x00007ffff6c70e8d in QtPrivate::QSlotObjectBase::call (a=<optimized out>, r=0x6f8da8, this=<optimized out>)
    at ../../include/QtCore/../../../../qt59/qtbase/src/corelib/kernel/qobject_impl.h:101
#20 QMetaObject::activate (sender=sender@entry=0x6fa860, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, 
    argv=argv@entry=0x7fffffffdae0) at /home/rutledge/dev/qt59/qtbase/src/corelib/kernel/qobject.cpp:3749
#21 0x00007ffff6c713ef in QMetaObject::activate (sender=sender@entry=0x6fa860, 
    m=m@entry=0x7ffff6f30680 <QSocketNotifier::staticMetaObject>, local_signal_index=local_signal_index@entry=0, 
    argv=argv@entry=0x7fffffffdae0) at /home/rutledge/dev/qt59/qtbase/src/corelib/kernel/qobject.cpp:3628
#22 0x00007ffff6cf46d7 in QSocketNotifier::activated (this=this@entry=0x6fa860, _t1=<optimized out>, _t2=...)
    at .moc/moc_qsocketnotifier.cpp:137
#23 0x00007ffff6c7d6e5 in QSocketNotifier::event (this=0x6fa860, e=<optimized out>)
    at /home/rutledge/dev/qt59/qtbase/src/corelib/kernel/qsocketnotifier.cpp:266
#24 0x00007ffff6c41a6e in QCoreApplicationPrivate::notify_helper (receiver=receiver@entry=0x6fa860, event=event@entry=0x7fffffffdc90)
    at /home/rutledge/dev/qt59/qtbase/src/corelib/kernel/qcoreapplication.cpp:1152
#25 0x00007ffff6c41af5 in doNotify (receiver=receiver@entry=0x6fa860, event=event@entry=0x7fffffffdc90)
    at /home/rutledge/dev/qt59/qtbase/src/corelib/kernel/qcoreapplication.cpp:1093
#26 0x00007ffff6c41beb in QCoreApplication::notify (this=this@entry=0x7fffffffdf60, receiver=receiver@entry=0x6fa860, 
    event=event@entry=0x7fffffffdc90) at /home/rutledge/dev/qt59/qtbase/src/corelib/kernel/qcoreapplication.cpp:1079
#27 0x00007ffff74d0261 in QGuiApplication::notify (this=0x7fffffffdf60, object=0x6fa860, event=0x7fffffffdc90)
    at /home/rutledge/dev/qt59/qtbase/src/gui/kernel/qguiapplication.cpp:1675
#28 0x00007ffff6c41b92 in QCoreApplication::notifyInternal2 (receiver=0x6fa860, event=event@entry=0x7fffffffdc90)
    at /home/rutledge/dev/qt59/qtbase/src/corelib/kernel/qcoreapplication.cpp:1018
#29 0x00007ffff6c9b70e in QCoreApplication::sendEvent (event=0x7fffffffdc90, receiver=<optimized out>)
    at ../../include/QtCore/../../../../qt59/qtbase/src/corelib/kernel/qcoreapplication.h:233
#30 socketNotifierSourceDispatch (source=0x681ab0) at /home/rutledge/dev/qt59/qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:106
#31 0x00007ffff465c7b7 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#32 0x00007ffff465ca20 in ?? () from /usr/lib/libglib-2.0.so.0
#33 0x00007ffff465cacc in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#34 0x00007ffff6c9a8c2 in QEventDispatcherGlib::processEvents (this=0x683230, flags=...)
    at /home/rutledge/dev/qt59/qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:423
#35 0x00007ffff273573e in QPAEventDispatcherGlib::processEvents (this=<optimized out>, flags=...)
    at /home/rutledge/dev/qt59/qtbase/src/platformsupport/eventdispatchers/qeventdispatcher_glib.cpp:122
#36 0x00007ffff6c3fc25 in QEventLoop::processEvents (this=this@entry=0x7fffffffdef0, flags=..., flags@entry=...)
    at /home/rutledge/dev/qt59/qtbase/src/corelib/kernel/qeventloop.cpp:134
#37 0x00007ffff6c40051 in QEventLoop::exec (this=this@entry=0x7fffffffdef0, flags=flags@entry=...)
    at /home/rutledge/dev/qt59/qtbase/src/corelib/kernel/qeventloop.cpp:212
#38 0x00007ffff6c49768 in QCoreApplication::exec () at /home/rutledge/dev/qt59/qtbase/src/corelib/kernel/qcoreapplication.cpp:1291
#39 0x00007ffff74cb474 in QGuiApplication::exec () at /home/rutledge/dev/qt59/qtbase/src/gui/kernel/qguiapplication.cpp:1666
#40 0x00000000004010a6 in main (argc=1, argv=0x7fffffffe0c8) at main.cpp:14
```

My shell is fish ATM; I wouldn't be surprised if there is some bug related to ANSI colors and such.  It has happened before with yat.  And my fork of yat does the same thing, so it's not just this one.  Last time I used it, I wasn't running fish.

A possible workaround would be to handle command-line arguments so that it's possible to try a different shell.

**Comment by rburchell** [comment]
There is a known bug with some things going out of bounds, and cursor access is one of them. Did you resize your window at all? Could be #10 if so.

**Comment by ec1oud** [comment]
No I didn't get a chance to resize, it crashes right away.  Probably due to some codes the shell is sending on startup.

**Comment by rburchell** [comment]
I'm not able to replicate any crash caused by fish at least.

For the record, you can either chsh to change the default shell, or export SHELL=$(which myshell) before starting to get something other than the default.

Could be interesting to get parser debug to see what exactly is coming in that makes it choke...

**Comment by rburchell** [comment]
I decided to take a different approach that I'd been thinking about for a while, and am building on top of fingerterm (Jolla's terminal, also dates back to N9 times etc). It's going to require some more work to clean up and split the terminal into a reusable component, but I think it's the better solution in the long term.

See https://github.com/rburchell/literm for the new code.

**Comment by rburchell** [comment]
Dead repo now.
